# In this notebook we will be gathering, assessing, cleaning, analyzing, and visualizing data

In [31]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import requests
import json

## Gathering data

In [32]:
# load the csv file into a DataFrame
tw_ar_en_df = pd.read_csv('twitter-archive-enhanced.csv')
tw_ar_en_df.head(2)

,tweet_id,in_reply_to_status_id,in_reply_to_user_id,timestamp,source,text,retweeted_status_id,retweeted_status_user_id,retweeted_status_timestamp,expanded_urls,rating_numerator,rating_denominator,name,doggo,floofer,pupper,puppo
0,892420643555336193,NaN,NaN,2017-08-01 16:23:56 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This is Phineas. He's a mystical boy. Only eve...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/892420643...,13,10,Phineas,None,None,None,None
1,892177421306343426,NaN,NaN,2017-08-01 00:17:27 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This is Tilly. She's just checking pup on you....,NaN,NaN,NaN,https://twitter.com/dog_rates/status/892177421...,13,10,Tilly,None,None,None,None

In [33]:
url = 'https://d17h27t6h515a5.cloudfront.net/topher/2017/August/599fd2ad_image-predictions/image-predictions.tsv'
img_req = requests.get(url, allow_redirects=True)

open('image_predictions.tsv', 'wb').write(img_req.content)
images_df = pd.read_csv('image_predictions.tsv', sep = '\t')
images_df.head()

,tweet_id,jpg_url,img_num,p1,p1_conf,p1_dog,p2,p2_conf,p2_dog,p3,p3_conf,p3_dog
0,666020888022790149,https://pbs.twimg.com/media/CT4udn0WwAA0aMy.jpg,1,Welsh_springer_spaniel,0.465074,True,collie,0.156665,True,Shetland_sheepdog,0.061428,True
1,666029285002620928,https://pbs.twimg.com/media/CT42GRgUYAA5iDo.jpg,1,redbone,0.506826,True,miniature_pinscher,0.074192,True,Rhodesian_ridgeback,0.072010,True
2,666033412701032449,https://pbs.twimg.com/media/CT4521TWwAEvMyu.jpg,1,German_shepherd,0.596461,True,malinois,0.138584,True,bloodhound,0.116197,True
3,666044226329800704,https://pbs.twimg.com/media/CT5Dr8HUEAA-lEu.jpg,1,Rhodesian_ridgeback,0.408143,True,redbone,0.360687,True,miniature_pinscher,0.222752,True
4,666049248165822465,https://pbs.twimg.com/media/CT5IQmsXIAAKY4A.jpg,1,miniature_pinscher,0.560311,True,Rottweiler,0.243682,True,Doberman,0.154629,True

In [34]:
import os
print(os.getcwd())
arr = os.listdir('.')
print(arr)

/Users/pp/Documents/Udacity/Wrangle and Analyze Data
['wrangle_act.ipynb', 'twitter-archive-enhanced.csv', '.DS_Store', 'twitter-archive-enhanced-2.csv', 'image_predictions.tsv', 'Untitled.ipynb', 'twitter_api.ipynb', 'image-predictions-3.tsv', '.ipynb_checkpoints', 'image-predictions.tsv', 'tweet_json.txt', 'tweet-json.zip']

In [43]:
# Loading the Twitter data without creating Twitter account
tw_counts_df = pd.read_json('tweet_json.txt')
#tw_counts_df = pd.read_csv(open("tweet_json.txt", "r", encoding="utf8"))
tw_counts_df.head(5)

ValueError: Trailing data